root:
  _type: array
  _children:
    state:
      _type: enum
      _values:
        - site
    settings:
      _type: array
      _children:
        title:
          _type: text
          _required: false
        description:
          _type: text
          _required: false
        date_format:
          _type: text
          _required: false
        time_format:
          _type: text
          _required: false
        active_theme:
          _type: text
          _required: false
        active_plugins:
          _type: prototype
          _prototype:
            _type: text
        default_role:
          _type: text
          _required: false
    users:
      _type: prototype
      _prototype:
        _type: array
        _children:
          display_name:
            _type: text
            _required: false
          email:
            _type: text
            _required: false
          role:
            _type: text
            _required: false
    terms:
      _type: prototype
      _prototype:
        _type: prototype
        _prototype:
          _type: array
          _children:
            name:
              _type: text
              _required: false
            description:
              _type: text
              _required: false
            parent:
              _type: text
              _required: false
